"""Utilities to extract frames from animated GIFs for PDF animation via LaTeX."""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

from PIL import Image, ImageSequence

DEFAULT_GIF = Path("data/plots/pole_balancing_100k.gif")
DEFAULT_OUTPUT = Path("data/plots/pole_balancing_100k_frames")
MANIFEST_TEX = "manifest.tex"
MANIFEST_JSON = "manifest.json"


@dataclass(frozen=True)
class ExtractionSummary:
    frame_count: int
    base_name: str
    fps: float
    durations_ms: List[int]

    def to_json(self) -> str:
        return json.dumps(
            {
                "frame_count": self.frame_count,
                "base_name": self.base_name,
                "fps": self.fps,
                "durations_ms": self.durations_ms,
            },
            indent=2,
        )

    def to_tex(self) -> str:
        last_index = max(0, self.frame_count - 1)
        lines = [
            "% Auto-generated by gif_to_frames.py -- DO NOT EDIT MANUALLY",
            "\\newcommand{\\PoleBalancingFrameBase}{%s}" % self.base_name,
            "\\newcommand{\\PoleBalancingFrameCount}{%d}" % self.frame_count,
            "\\newcommand{\\PoleBalancingFrameLast}{%d}" % last_index,
            "\\newcommand{\\PoleBalancingFrameFPS}{%.3f}" % self.fps,
        ]
        return "\n".join(lines) + "\n"


@dataclass
class ExtractionConfig:
    gif_path: Path
    output_dir: Path
    prefix: str
    step: int
    max_frames: int | None
    clear_output: bool


def parse_args() -> ExtractionConfig:
    parser = argparse.ArgumentParser(
        description="Extract GIF frames as PNGs and emit metadata for LaTeX animategraphics.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--gif", type=Path, default=DEFAULT_GIF, help="Path to the GIF file to extract")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Directory for extracted PNG frames and manifest files",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default=None,
        help="Prefix for frame filenames. Defaults to GIF stem.",
    )
    parser.add_argument(
        "--step",
        type=int,
        default=1,
        help="Only keep every N-th frame (higher values reduce total frame count).",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=None,
        help="Optional hard cap on the number of frames to export.",
    )
    parser.add_argument(
        "--no-clear",
        dest="clear_output",
        action="store_false",
        help="Keep existing frame PNG files in the output directory.",
    )
    parser.set_defaults(clear_output=True)

    args = parser.parse_args()

    gif_path = args.gif.resolve() if not args.gif.is_absolute() else args.gif
    output_dir = args.output_dir.resolve() if not args.output_dir.is_absolute() else args.output_dir
    prefix = args.prefix or gif_path.stem

    if args.step <= 0:
        raise SystemExit("--step must be a positive integer")
    if args.max_frames is not None and args.max_frames <= 0:
        raise SystemExit("--max-frames must be positive when provided")

    return ExtractionConfig(
        gif_path=gif_path,
        output_dir=output_dir,
        prefix=prefix,
        step=args.step,
        max_frames=args.max_frames,
        clear_output=args.clear_output,
    )


def iter_frames(path: Path) -> Iterable[Image.Image]:
    if not path.exists():
        raise FileNotFoundError(path)
    with Image.open(path) as img:
        for frame in ImageSequence.Iterator(img):
            yield frame.copy()


def compute_fps(durations: Iterable[int]) -> float:
    durations_list = [max(1, int(d)) for d in durations]
    if not durations_list:
        return 24.0
    average_ms = sum(durations_list) / len(durations_list)
    if average_ms <= 0:
        return 24.0
    return 1000.0 / average_ms


def clear_existing_frames(directory: Path, prefix: str) -> None:
    if not directory.exists():
        return
    for path in directory.glob(f"{prefix}-*.png"):
        path.unlink(missing_ok=True)
    for manifest in (MANIFEST_TEX, MANIFEST_JSON):
        candidate = directory / manifest
        if candidate.exists():
            candidate.unlink()


def extract_frames(config: ExtractionConfig) -> ExtractionSummary:
    frames = []
    durations: List[int] = []

    for index, frame in enumerate(iter_frames(config.gif_path)):
        if index % config.step != 0:
            continue
        if config.max_frames is not None and len(frames) >= config.max_frames:
            break
        durations.append(int(frame.info.get("duration", 100)))
        frames.append(frame.convert("RGBA"))

    if not frames:
        raise RuntimeError("No frames extracted. Try adjusting --step or check the GIF file.")

    config.output_dir.mkdir(parents=True, exist_ok=True)
    if config.clear_output:
        clear_existing_frames(config.output_dir, config.prefix)

    for idx, frame in enumerate(frames):
        filename = f"{config.prefix}-{idx}.png"
        frame.save(config.output_dir / filename)

    fps = compute_fps(durations)
    summary = ExtractionSummary(
        frame_count=len(frames),
        base_name=config.prefix,
        fps=fps,
        durations_ms=durations,
    )

    manifest_tex_path = config.output_dir / MANIFEST_TEX
    manifest_tex_path.write_text(summary.to_tex(), encoding="utf-8")

    manifest_json_path = config.output_dir / MANIFEST_JSON
    manifest_json_path.write_text(summary.to_json(), encoding="utf-8")

    return summary


def main() -> None:
    config = parse_args()
    summary = extract_frames(config)
    print(
        "Exported {count} frames to {output}\nBase name: {base}\nFPS: {fps:.2f}".format(
            count=summary.frame_count,
            output=config.output_dir,
            base=summary.base_name,
            fps=summary.fps,
        )
    )


if __name__ == "__main__":
    main()
